### ISSUE TITLE
[flawhud] Spectator text cut off with 32 person scoreboard

### ISSUE THREAD

**Issue by yslupdates** [CriticalFlaw/TF2HUD.Editor#183]
Hi

I use flawhud on a 2560x1440 monitor with 32 person scoreboard. The spectator text is cut off about halfway at the bottom and the 32 person scoreboard view is a bit off-center. I can imagine that it's center in the 24 person scoreboard but it's a bit low for 32. I updated to the latest version via tf2hudeditor today.

Thank you

![20230404205400_1](https://user-images.githubusercontent.com/53108354/229977320-503b85b6-4222-41f6-a4d3-70935d6466e4.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 304d91a6d893e8e6f102cec4227de5615d5e7630. Below are the comparison screenshots. Thanks!

**Standard Scoreboard**
![20230408144615_1](https://user-images.githubusercontent.com/6818236/230737908-0f9f2c30-7e21-48b8-99a0-49b5c2569b34.jpg)

**Expanded Scoreboard**
![20230408144608_1](https://user-images.githubusercontent.com/6818236/230737907-a8a921f4-bde9-4811-a792-6645df9311bf.jpg)
