### ISSUE TITLE
[BUG] Hud editor not applying changes 

### ISSUE THREAD

**Issue by Deexe2137** [CriticalFlaw/TF2HUD.Editor#257]
I've recently updated to new version of flawhud since after scream fortress update the version of the hud i've been using has slightly broke (it was 2022 version), and by pressing "apply changes" chenges don't even apply 
 - OS: [Windows 10, x64]
 - App Version: [3.4]
 - Selected HUD: [flawhud]

**Comment by CriticalFlaw** [comment]
Can you try two things please:

1. In the editor, click on the wrench icon at the bottom right corner of the screen and select Clear Cache
2. In the same options menu select Check for Updates

**Comment by Deexe2137** [comment]
Thanks a lot, clearing chache worked. also, is there a way to get rid of those two masterconfig options from mode selection?
![obraz](https://github.com/user-attachments/assets/7a6afd9b-a616-4fd0-91c3-271e6380c8b0)

**Comment by Silexos** [comment]
Been having this issue too! I cleared the cache and checked for updates and flawhud has not applied any changes apart from colors. The issue still persists after a fresh install of both flawhud and the editor

**Comment by CriticalFlaw** [comment]
Can you post the log file produced by the editor? You may need to clear cache again

**Comment by Silexos** [comment]
Of course! Just cleared the cache and there are still some unregistered changes. Here's the log and a screenshot of the selected custom options (the health style is 'colored text, no box'). 

[20241025.log](https://github.com/user-attachments/files/17527560/20241025.log)
![Capture](https://github.com/user-attachments/assets/915f24ba-e05a-46a2-b92e-40cf886f5291)

**Comment by CriticalFlaw** [comment]
Thanks. Which options in particular are not applying? The backgrounds are currently being overwritten by seasonal backgrounds which is by design. The rest I've tested and they work fine. I'd suggest clearing the cache one more time and restarting your PC. It seems to be a long running issue that users get resolved after a few clear attempts. Sorry in advance for the inconvenience.

![image](https://github.com/user-attachments/assets/9e990079-795e-4ada-9af3-deb34082f359)

![20241105220600_1](https://github.com/user-attachments/assets/572a47cb-d831-437d-9e20-85ade2afbc78)

![20241105220606_1](https://github.com/user-attachments/assets/892f6abd-ffc5-40f0-b57c-a5de51a4f8dc)

![20241105220645_1](https://github.com/user-attachments/assets/9f7385f9-0683-4c2c-b124-35a116961f6f)

**Comment by Silexos** [comment]
No problem! Ended up clearing the cache 7-10 times and now everything is applying properly. Thanks again!

**Comment by CriticalFlaw** [comment]
Holy crap. Sorry about that but glad it's now working
