### ISSUE TITLE
Add streamer mode to the default HUD

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/TF2HUD.Editor#53]
It would added here: https://github.com/CriticalFlaw/TF2HUD.Editor/blob/master/src/TF2HUD.Editor/JSON/default.json

Could use flawhud as a point of reference for the files that need to be updated.

**Comment by rbjaxter** [comment]
Depending on how you're intending to implement it, peeping budhud's stream folder may also help find the specific files and lines (since the only things in these files are there for the stream hud):
https://github.com/rbjaxter/budhud/tree/master/_stream_

Not sure if you have the stream hud implemented the same way in flawhud, but if not it may help make it a bit easier for you

**Comment by CriticalFlaw** [comment]
Following files will need to be added to https://github.com/CriticalFlaw/TF2HUD.Plus for this feature to work completely.
- resource/ui/dashboardpartymember.res
- resource/ui/disguisestatuspanel.res
- resource/ui/freezepanel_basic.res
- resource/ui/hudarenawinpanel.res
- resource/ui/hudinspectpanel.res
- resource/ui/hudkillstreaknotice.res
- resource/ui/hudmatchsummary.res
- resource/ui/hudtournament.res
- resource/ui/matchmakingtooltip.res
- resource/ui/mvmscoreboard.res
- resource/ui/mvmvictorymannupentry.res
- resource/ui/scoreboard.res
- resource/ui/targetid.res
- resource/ui/votehud.res
- resource/ui/winpanel.res

**Comment by CriticalFlaw** [comment]
Implemented in f1abd2db4da82d646d49a612952cd348d6409788
