### ISSUE TITLE
Change shadow color in other HUDs.

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/TF2HUD.Editor#71]
I think it would be beneficial to have an option to change the background shadow for health and ammo available for all currently supported huds. The feature is quite useful in the Zeeshud section and I could see it being a nice quality of life change if applied to the other huds as well. In addition maybe a toggle option for colored shadows could be implemented in the user interface.

**Comment by CriticalFlaw** [comment]
Part of the vision for the editor is to give other HUD authors the ability to build their own _HUD Customizer_. While we can add colored shadow options to flawhud or rayshud (because I'm their maintainer), we can't do the same for other HUDs unless their authors want that to be a customization option. They can add those options themselves or ask us to, but then they would also have to update their HUDs to have multiple shadow variables for the editor to update.

**Comment by CriticalFlaw** [comment]
The best approach is to reach out to the HUD author and have them update their HUD to have individual shadows for health, ammo etc. then either have them or ask us to implement changing those colors in the editor.

**Comment by Silexos** [comment]
Ah makes sense. The idea would definitely conflict with the vision of the editor and I respect keeping true to your vision. In any case great work on the editor and I wish you the best!

**Comment by CriticalFlaw** [comment]
> Ah makes sense. The idea would definitely conflict with the vision of the editor and I respect keeping true to your vision. In any case great work on the editor and I wish you the best!

Thank you for the response and the suggestion. It's really appreciated :)
